"""
utils.py - Core Helper Utilities for License Plate Super-Resolution.

This module provides essential support functions for:
    - Image Preprocessing: Perspective rectification (deskewing) and padding.
    - OCR Heuristics: Confusable character weights and Levenshtein distance.
    - Metrics: PSNR and SSIM for quantitative image quality assessment.
    - Monitoring: Dual-pipe logging and comprehensive training progress plotting.
    - Persistence: Model checkpointing and training state management.
"""

import os
import re
import cv2
import json
import logging
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import torch
from typing import Dict, List, Tuple, Any, Optional, Union
from pathlib import Path
from skimage.metrics import peak_signal_noise_ratio, structural_similarity


# ============================================================================
# Confusable Characters
# ============================================================================

# Characters that are easily confused with each other on license plates
CONFUSABLE_PAIRS = {
    'O': '0', '0': 'O',
    'I': '1', '1': 'I',
    'B': '8', '8': 'B',
    'D': '0',  # D looks like 0
    'S': '5', '5': 'S',
    'Z': '2', '2': 'Z',
    'G': '6', '6': 'G',
    'Q': '0',
    'L': '1',
    'T': '7', '7': 'T',
}

# Higher penalty weights for confusable character mismatches
CONFUSABLE_WEIGHT = 2.0  # 2x penalty for confusable char errors
NORMAL_WEIGHT = 1.0


def get_char_weights(gt_text: str, pred_text: str, num_chars: int = 7) -> List[float]:
    """
    Computes per-character loss weights based on OCR confusability heuristics.
    
    This function analyzes the predicted string against the ground truth. If a character
    is incorrectly predicted AND the mistake involves known confusable pairs (e.g., '0' vs 'O', '8' vs 'B'),
    the weight for that specific character position is exponentially increased to heavily penalize the model.
    This forces the Super-Resolution mechanism to synthesize these ambiguous characters much more cleanly.
    
    Args:
        gt_text (str): Ground truth alphanumeric plate text (e.g., "AVL5215").
        pred_text (str): Predicted alphanumeric plate text generated by the OCR module.
        num_chars (int, optional): The normalized length of the license plate. Defaults to 7.
    
    Returns:
        List[float]: A list of float weights, exactly `num_chars` elements long, to be multiplied by the baseline CE loss.
    """
    weights: List[float] = []
    min_len = min(len(gt_text), len(pred_text), num_chars)
    
    for i in range(num_chars):
        if i >= min_len:
            weights.append(CONFUSABLE_WEIGHT)  # Missing/extra chars get high weight
            continue
            
        gt_c = gt_text[i].upper()
        pr_c = pred_text[i].upper()
        
        if gt_c == pr_c:
            weights.append(NORMAL_WEIGHT)
        elif gt_c in CONFUSABLE_PAIRS and CONFUSABLE_PAIRS[gt_c] == pr_c:
            weights.append(CONFUSABLE_WEIGHT)
        elif pr_c in CONFUSABLE_PAIRS and CONFUSABLE_PAIRS[pr_c] == gt_c:
            weights.append(CONFUSABLE_WEIGHT)
        else:
            weights.append(NORMAL_WEIGHT)
    
    return weights


# ============================================================================
# Image Processing
# ============================================================================

def padding(img: np.ndarray, min_ratio: float, max_ratio: float, color: Tuple[int, int, int] = (127, 127, 127)) -> Tuple[np.ndarray, int, int]:
    """
    Pads an image with a solid color border to maintain an aspect ratio strictly within [min_ratio, max_ratio].
    
    This is highly useful for spatial transformers or CNN inputs, where severe distortion/stretching 
    might obliterate natural letter boundaries.
    
    Args:
        img (np.ndarray): The source image matrix.
        min_ratio (float): The minimum acceptable aspect ratio (width/height).
        max_ratio (float): The maximum acceptable aspect ratio (width/height).
        color (Tuple[int, int, int], optional): RGB background padding color. Defaults to (127, 127, 127).
        
    Returns:
        Tuple[np.ndarray, int, int]: The padded image, horizontal border width, vertical border height.
    """
    img_h, img_w = np.shape(img)[:2]
    border_w = 0
    border_h = 0
    ar = float(img_w) / img_h

    if ar >= min_ratio and ar <= max_ratio:
        return img, border_w, border_h

    if ar < min_ratio:
        while ar < min_ratio:
            border_w += 1
            ar = float(img_w + border_w) / (img_h + border_h)
    else:
        while ar > max_ratio:
            border_h += 1
            ar = float(img_w) / (img_h + border_h)

    border_w = border_w // 2
    border_h = border_h // 2

    img = cv2.copyMakeBorder(img, border_h, border_h, border_w, border_w,
                              cv2.BORDER_CONSTANT, value=color)
    return img, border_w, border_h


def rectify_image(img: np.ndarray, corners: Dict[str, List[float]], margin: int = 2) -> np.ndarray:
    """
    Rectify an obliquely captured license plate image using perspective transform algebra.
    
    Maps arbitrary quadrilateral coordinates (from object detection/landmarks) to a flat rectangular plane.
    
    Args:
        img (np.ndarray): The arbitrarily oriented input image array.
        corners (Dict[str, List[float]]): A dictionary denoting the four quadrilateral bounding box corners 
                                          in [X, Y] format: 'top-left', 'top-right', 'bottom-right', 'bottom-left'.
        margin (int, optional): The extra pixel border padded around the newly projected plate. Defaults to 2.
    
    Returns:
        np.ndarray: The flat, orthomosaic rectified image.
    """
    pts = np.array([
        corners['top-left'],
        corners['top-right'],
        corners['bottom-right'],
        corners['bottom-left']
    ], dtype='float32')
    
    (tl, tr, br, bl) = pts

    widthA = np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))
    widthB = np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))
    maxWidth = max(int(widthA), int(widthB))

    heightA = np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))
    heightB = np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))
    maxHeight = max(int(heightA), int(heightB))

    maxWidth += margin * 2
    maxHeight += margin * 2

    ww = maxWidth - 1 - margin
    hh = maxHeight - 1 - margin
    c1 = [margin, margin]
    c2 = [ww, margin]
    c3 = [ww, hh]
    c4 = [margin, hh]

    dst = np.array([c1, c2, c3, c4], dtype='float32')

    M = cv2.getPerspectiveTransform(pts, dst)
    warped = cv2.warpPerspective(img, M, (maxWidth, maxHeight))

    return warped


# ============================================================================
# Logging Setup
# ============================================================================

def setup_logging(save_dir: Union[Path, str], name: str = 'training') -> logging.Logger:
    """
    Bootstraps a professional dual-pipe logging system.
    
    Logs are simultaneously routed to:
      1. The system console (stdout) for real-time monitoring.
      2. A local filesystem `.log` file for long-term audit and debugging.
    
    Args:
        save_dir (Union[Path, str]): Directory where the log file will be archived.
        name (str): Semantic namespace for the logger instance.
    
    Returns:
        logging.Logger: The configured logger instance.
    """
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    
    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    
    # Clear existing handlers
    logger.handlers.clear()
    
    # Console handler
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch_fmt = logging.Formatter('[%(asctime)s] %(levelname)s: %(message)s', datefmt='%H:%M:%S')
    ch.setFormatter(ch_fmt)
    logger.addHandler(ch)
    
    # File handler
    fh = logging.FileHandler(save_dir / f'{name}.log', mode='a')
    fh.setLevel(logging.DEBUG)
    fh_fmt = logging.Formatter('[%(asctime)s] %(levelname)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
    fh.setFormatter(fh_fmt)
    logger.addHandler(fh)
    
    return logger


# ============================================================================
# Metrics
# ============================================================================

def calculate_psnr(img1: np.ndarray, img2: np.ndarray) -> float:
    """
    Calculates Peak Signal-to-Noise Ratio (PSNR) between two images.
    
    Args:
        img1 (np.ndarray): Reference (Ground Truth) image.
        img2 (np.ndarray): Recovered (Super-Resolved) image.
        
    Returns:
        float: The PSNR value in decibels (dB).
    """
    return peak_signal_noise_ratio(img1, img2)


def calculate_ssim(img1: np.ndarray, img2: np.ndarray) -> float:
    """
    Calculates Structural Similarity Index (SSIM) between two images.
    
    Uses a larger Gaussian weighting and accounts for RGB channels to ensure
    the metric matches human visual perception of alphanumeric clarity.
    
    Args:
        img1 (np.ndarray): Reference image.
        img2 (np.ndarray): Recovered image.
        
    Returns:
        float: SSIM index in range [0, 1].
    """
    return structural_similarity(
        img1, img2,
        gaussian_weights=True,
        channel_axis=2,
        sigma=1.5,
        use_sample_covariance=False,
        data_range=255.0
    )


def levenshtein(a: str, b: str) -> int:
    """
    Calculates the Levenshtein (Edit) distance between two strings.
    
    Used to quantify character-level prediction errors during training.
    
    Args:
        a (str): Source string (Ground Truth).
        b (str): Target string (SR Prediction).
        
    Returns:
        int: Minimum number of single-character edits required to transform a to b.
    """
    if not a:
        return len(b)
    if not b:
        return len(a)
    
    # Iterative DP version (avoids recursion stack overflow)
    m, n = len(a), len(b)
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    
    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            cost = 0 if a[i - 1] == b[j - 1] else 1
            dp[i][j] = min(
                dp[i - 1][j] + 1,      # deletion
                dp[i][j - 1] + 1,      # insertion
                dp[i - 1][j - 1] + cost  # substitution
            )
    
    return dp[m][n]


# ============================================================================
# Plotting
# ============================================================================

def plot_losses(train_losses: List[float], val_losses: List[float], 
                save_path: Union[Path, str], title: str = 'Training Progress') -> None:
    """
    Renders and saves a Dual-Axis loss curve over the training duration.
    
    This function automatically aligns validation checkpoints with training 
    epochs for accurate visual comparison. It also highlights the 'Best' 
    validation epoch with a green annotation.
    
    Args:
        train_losses (List[float]): Training loss values per epoch.
        val_losses (List[float]): Validation loss values (calculated periodically).
        save_path (Union[Path, str]): Output path for the PNG chart.
        title (str): Title of the plot.
    """
    fig, ax = plt.subplots(1, 1, figsize=(12, 6))
    
    epochs = range(1, len(train_losses) + 1)
    ax.plot(epochs, train_losses, 'b-o', label='Train Loss', linewidth=2, markersize=4)
    
    if len(val_losses) > 0:
        # Calculate validation epochs based on the ratio of lengths
        # e.g., if train=100 and val=10, interval is 10, so val_epochs=[10, 20... 100]
        interval = len(train_losses) // len(val_losses)
        val_epochs = [i * interval for i in range(1, len(val_losses) + 1)]
        
        # Ensure lengths match for plotting
        v_limit = min(len(val_epochs), len(val_losses))
        ax.plot(val_epochs[:v_limit], val_losses[:v_limit], 'r-s', label='Val Loss', linewidth=2, markersize=4)
        
        # Mark best validation performance
        best_idx = np.argmin(val_losses)
        if best_idx < len(val_epochs):
            best_epoch = val_epochs[best_idx]
            ax.annotate(f'Best: {val_losses[best_idx]:.4f}\n(Epoch {best_epoch})',
                        xy=(best_epoch, val_losses[best_idx]),
                        xytext=(best_epoch + max(1, len(epochs) * 0.05), val_losses[best_idx]),
                        arrowprops=dict(arrowstyle='->', color='green'),
                        fontsize=10, color='green')
    
    ax.set_xlabel('Epochs', fontsize=12)
    ax.set_ylabel('Loss', fontsize=12)
    ax.set_title(title, fontsize=14)
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)


def plot_metrics(psnr_list: List[float], ssim_list: List[float], 
                 save_path: Union[Path, str], title: str = 'Metrics Progress') -> None:
    """
    Renders and saves dual charts for PSNR and SSIM progression.
    
    Args:
        psnr_list (List[float]): History of PSNR values.
        ssim_list (List[float]): History of SSIM values.
        save_path (Union[Path, str]): File output path.
        title (str): Global title.
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    
    # Metrics are only recorded on validation epochs
    # We use the length of the metric lists and label them as checkpoints
    checkpoints = range(1, len(psnr_list) + 1)
    
    ax1.plot(checkpoints, psnr_list, 'g-o', linewidth=2, markersize=4)
    ax1.set_xlabel('Validation Checkpoint', fontsize=12)
    ax1.set_ylabel('PSNR (dB)', fontsize=12)
    ax1.set_title('PSNR over Checkpoints', fontsize=14)
    ax1.grid(True, alpha=0.3)
    
    ax2.plot(checkpoints, ssim_list, 'm-s', linewidth=2, markersize=4)
    ax2.set_xlabel('Validation Checkpoint', fontsize=12)
    ax2.set_ylabel('SSIM', fontsize=12)
    ax2.set_title('SSIM over Checkpoints', fontsize=14)
    ax2.grid(True, alpha=0.3)
    
    plt.suptitle(title, fontsize=15, y=1.02)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)


def plot_confusion_matrix(cm, classes, save_path, title='Character Confusion Matrix',
                          normalize=True):
    """
    Plot confusion matrix for character recognition.
    
    Args:
        cm: Confusion matrix (numpy array)
        classes: List of class labels
        save_path: Path to save figure
        title: Plot title
        normalize: Whether to normalize the CM
    """
    if normalize:
        row_sums = cm.sum(axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1  # avoid div by zero
        cm_norm = cm.astype('float') / row_sums
    else:
        cm_norm = cm
    
    fig, ax = plt.subplots(figsize=(16, 14))
    
    im = ax.imshow(cm_norm, interpolation='nearest', cmap='Blues')
    ax.set_title(title, fontsize=16, pad=20)
    
    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label('Proportion' if normalize else 'Count', fontsize=12)
    
    tick_marks = np.arange(len(classes))
    ax.set_xticks(tick_marks)
    ax.set_xticklabels(classes, fontsize=8, rotation=45)
    ax.set_yticks(tick_marks)
    ax.set_yticklabels(classes, fontsize=8)
    
    ax.set_ylabel('Ground Truth', fontsize=14)
    ax.set_xlabel('Predicted', fontsize=14)
    
    # Add text annotations for non-zero cells
    thresh = cm_norm.max() / 2.0
    for i in range(len(classes)):
        for j in range(len(classes)):
            if cm[i, j] > 0:  # Only show non-zero
                ax.text(j, i, f'{cm[i, j]}',
                        ha='center', va='center', fontsize=6,
                        color='white' if cm_norm[i, j] > thresh else 'black')
    
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)


def build_confusion_matrix(gt_texts, pred_texts):
    """
    Build per-character confusion matrix.
    
    Args:
        gt_texts: List of ground truth plate texts
        pred_texts: List of predicted plate texts
    
    Returns:
        cm: Confusion matrix (36x36 for A-Z + 0-9)
        classes: List of class labels
    """
    classes = [chr(i) for i in range(ord('A'), ord('Z') + 1)] + \
              [str(i) for i in range(10)]
    class_to_idx = {c: i for i, c in enumerate(classes)}
    
    n = len(classes)
    cm = np.zeros((n, n), dtype=int)
    
    for gt, pred in zip(gt_texts, pred_texts):
        min_len = min(len(gt), len(pred))
        for i in range(min_len):
            gt_c = gt[i].upper()
            pr_c = pred[i].upper()
            if gt_c in class_to_idx and pr_c in class_to_idx:
                cm[class_to_idx[gt_c], class_to_idx[pr_c]] += 1
    
    return cm, classes


# ============================================================================
# Checkpoint Helpers
# ============================================================================

def save_training_state(state: Dict[str, Any], path: Union[Path, str], filename: str) -> None:
    """
    Serializes and saves the complete training environment.
    
    Includes model weights, optimizer state, epoch count, and training history.
    
    Args:
        state (Dict[str, Any]): Dictionary of objects to preserve.
        path (Union[Path, str]): Directory to save.
        filename (str): Target filename (e.g., 'bestmodel.pt').
    """
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    torch.save(state, path / filename)


def load_training_state(path: Union[Path, str]) -> Dict[str, Any]:
    """
    Restores the training environment from a saved checkpoint.
    
    Args:
        path (Union[Path, str]): Path to the `.pt` file.
        
    Returns:
        Dict[str, Any]: The loaded state dictionary.
    """
    return torch.load(path, map_location='cpu', weights_only=False) # type: ignore

# ============================================================================
# Visual Comparison Grid
# ============================================================================

def save_comparison_grid(lr_tensors: torch.Tensor, sr_tensors: torch.Tensor, 
                         hr_tensors: torch.Tensor, gt_plates: List[str], 
                         ocr_module: Optional[Any], save_path: Union[Path, str], 
                         num_samples: int = 4) -> None:
    """
    Generates a high-quality visualization grid comparing quality levels.
    
    Row structure:
      1. LR (Bicubic Upsampled): Baseline low quality.
      2. SR (Model Output): Enhanced quality with OCR logic results.
      3. HR (Ground Truth): Target professional quality.
    
    Args:
        lr_tensors (torch.Tensor): Original LR inputs.
        sr_tensors (torch.Tensor): Model super-resolved outputs.
        hr_tensors (torch.Tensor): High-res targets.
        gt_plates (List[str]): Verified ground truth texts.
        ocr_module (Optional[Any]): The OCR module instance to run live prediction on SR.
        save_path (Union[Path, str]): Output PNG path.
        num_samples (int): Max columns in the grid.
    """
    num_samples = min(num_samples, lr_tensors.size(0))
    
    # Ensure save directory exists
    save_path = Path(save_path)
    save_path.parent.mkdir(parents=True, exist_ok=True)
    
    fig, axes = plt.subplots(3, num_samples, figsize=(5 * num_samples, 10))
    
    # Ensure axes is 2D even if num_samples=1
    if num_samples == 1:
        axes = np.expand_dims(axes, axis=1)
        
    for i in range(num_samples):
        # 1. LR (upscaled for comparison)
        lr_np = lr_tensors[i].cpu().permute(1, 2, 0).numpy()
        lr_np = np.clip(lr_np, 0, 1)
        lr_up = cv2.resize(lr_np, (hr_tensors.size(3), hr_tensors.size(2)), interpolation=cv2.INTER_LINEAR)
        axes[0, i].imshow(lr_up)
        axes[0, i].set_title(f"LR #{i}\nGT: '{gt_plates[i]}'")
        axes[0, i].axis('off')
        
        # 2. SR
        sr_np_torch = sr_tensors[i].cpu().detach()
        sr_np = sr_np_torch.permute(1, 2, 0).numpy()
        sr_np = np.clip(sr_np, 0, 1)
        
        # Predict on SR using OCR
        import torch
        from torchvision import transforms
        to_pil = transforms.ToPILImage()
        sr_pil_np = np.array(to_pil(sr_np_torch)).astype('uint8')
        pred = ocr_module.predict_plate(sr_pil_np) if ocr_module else "N/A"
        
        axes[1, i].imshow(sr_np)
        axes[1, i].set_title(f"SR #{i}\nOCR: '{pred}'")
        axes[1, i].axis('off')
        
        # 3. HR (Ground Truth)
        hr_np = hr_tensors[i].cpu().permute(1, 2, 0).numpy()
        hr_np = np.clip(hr_np, 0, 1)
        axes[2, i].imshow(hr_np)
        axes[2, i].set_title(f"HR (GT) #{i}")
        axes[2, i].axis('off')
        
    plt.tight_layout()
    plt.savefig(save_path, dpi=120, bbox_inches='tight')
    plt.close(fig)
